language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls

# command to run tests
script:
  - coverage run setup.py test

after_success:
  - coveralls
